"""Forcing Null set

Revision ID: 8a0b523e5af5
Revises: 44721db73673
Create Date: 2024-12-15 11:15:11.183575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a0b523e5af5'
down_revision: Union[str, None] = '44721db73673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
